version: "3.6"
services:
    tivoli-shared-desktop:
        image: tivolicloud/shared-desktop:latest
        # restart: always
        # runtime: nvidia # enable for nvidia encoding
        # devices: [/dev/dri/renderD128:/dev/dri/renderD128] # enable for vaapi encoding (amd or intel quicksync)
        cap_add:
            - SYS_ADMIN # necessary for chrome sandboxing
        volumes:
            - /dev/shm:/dev/shm # fixes memory crashes in chrome
        dns: # use cloudflare dns to block bad things
            - "1.1.1.3"
            - "1.0.0.3"
        ports:
            - 8080:80/tcp
            - 10000-10199:10000-10199/udp
        environment:
            - RTP_PORT_RANGE=10000-10199
            - PUBLIC_IP=getmypublicip # set to `getmypublicip` or specify manually
            - CODEC=h264 # or vp8 (not recommended)
            - PASSWORD= # empty means no password (set with ?password=)
            - ALLOW_STEAL=true # allows stealing each other's controls
            - DESKTOP_RES=1366x768
            - STREAM_RES=1280x720
            - STREAM_BITRATE=4000 # 5000 for 1080p
