version: "3.6"
services:
    tivoli-shared-desktop:
        image: tivolicloud/shared-desktop:latest
        # restart: always
        # runtime: nvidia
        ports:
            - 8080:80/tcp
            - 10000-10199:10000-10199/udp
        environment:
            - RTP_PORT_RANGE=10000-10199
            - DOCKER_IP=172.17.0.1 # public ip or `ip addr | grep docker`
            - CODEC=h264 # or vp8 (not recommended)
            - PASSWORD= # empty means no password (set with ?password=)
            - ALLOW_STEAL=true # allows stealing each other's controls
