version: "3.6"
services:
    tivoli-shared-desktop:
        image: tivolicloud/shared-desktop:latest
        # restart: always
        ports:
            - 8080:80/tcp
            - 10000-10200:10000-10200/udp
        environment:
            - DOCKER_IP=172.17.0.1 # public ip or `ip addr | grep docker`
